### ISSUE TITLE
PMC support not found; unrecognized AMD family 6

### ISSUE THREAD

**Issue by Allen3** [dedis/Determinator#2]
I successfully compiled the `Determinator` kernel and loaded the "kernel.img" image file into the QEMU to launch the OS.
However, I got such a response and wondered what the "PMC support" is. The screenshot image is as follow: https://drive.google.com/file/d/1SKMG1KB1qprESAJ7oxgaVL04e9dFLt1M/view?usp=sharing
I ran this QEMU thing on a remote server and it is `x86_64` architecture. 

Would u direct me to the PMC support or give me some hint? Thanks.

**Comment by jeffallen** [comment]
Sorry, this repository is no longer supported. If you find a solution to your problem, please post it here to help others. If it's a code change, you are welcome to send a PR. We are unlikely to merge it, but that way, it will be here so that others can use it as well.

Thank you for your interest in Determinator.
